AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AI Image Analyzer

  Sample SAM Template for AI Image Analyzer

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.12
    Architectures:
      - x86_64
    Layers:
      - !Sub arn:aws:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPythonV3-python312-x86_64:18
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: ai-image-analyzer
        POWERTOOLS_METRICS_NAMESPACE: MyCoolApp
        LOG_LEVEL: INFO
        DDB_TABLE_NAME: !Ref ImageAnalysisTable

Resources:
  ImageAnalysisFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.handler
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub '${AWS::StackName}-uploads'
        - DynamoDBCrudPolicy:
            TableName: !Ref ImageAnalysisTable
        - RekognitionDetectOnlyPolicy: {}
        - Statement:
          - Effect: Allow
            Action:
              - bedrock:InvokeModel
            Resource: '*' 
      FunctionUrlConfig:
        AuthType: NONE

  ImageAnalysisTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  UploadsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-uploads'

Outputs:
  ImageAnalysisApi:
    Description: "API Gateway endpoint URL for Prod stage for Image Analysis function"
    Value: !GetAtt ImageAnalysisFunctionUrl.FunctionUrl